backend:
  name: github
  repo: WilliamK-01/EMSChaplaincyWebsite
  branch: main
  base_url: https://auth.emschaplaincy.site
  auth_endpoint: /auth

media_folder: "assets/blog"
public_folder: "/assets/blog"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "blog/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Featured Image", name: "featured_image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
